package com.supportdesk.support;

import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Bean;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * PostgreSQL for integration tests (rules/testing.md §4): same major version as production (ADR-0001, A-2), the
 * Debian-based image so the database has a UTF-8 locale for case-insensitive search (review SR-05). Credentials are
 * generated by Testcontainers. Spring's context cache shares one container across test classes with the same setup.
 */
@TestConfiguration(proxyBeanMethods = false)
public class PostgresTestcontainer {

    public static final DockerImageName IMAGE = DockerImageName.parse("postgres:17");

    @Bean
    @ServiceConnection
    PostgreSQLContainer postgres() {
        return new PostgreSQLContainer(IMAGE);
    }
}
